// Code generated by "stringer -type=TTy"; DO NOT EDIT.

package internal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[EOF-1]
	_ = x[EQL-2]
	_ = x[NEQ-3]
	_ = x[INC-4]
	_ = x[DEC-5]
	_ = x[ANDEQL-6]
	_ = x[OREQL-7]
	_ = x[XOREQL-8]
	_ = x[ADDEQL-9]
	_ = x[SUBEQL-10]
	_ = x[MINUS-11]
	_ = x[LBRACK-12]
	_ = x[RBRACK-13]
	_ = x[LPAREN-14]
	_ = x[RPAREN-15]
	_ = x[COLON-16]
	_ = x[FN-17]
	_ = x[BEGIN-18]
	_ = x[END-19]
	_ = x[RETURN-20]
	_ = x[IF-21]
	_ = x[THEN-22]
	_ = x[NOT-23]
	_ = x[SECTION-24]
	_ = x[CONSTANTS-25]
	_ = x[DATA-26]
	_ = x[PROGRAM-27]
	_ = x[CONFIGURATION-28]
	_ = x[BANKED-29]
	_ = x[COMMON-30]
	_ = x[I8-31]
	_ = x[AT-32]
	_ = x[IDENT-33]
	_ = x[NUM_First-34]
	_ = x[NUMDECIMAL-35]
	_ = x[NUMHEX-36]
	_ = x[NUMBINARY-37]
	_ = x[NUM_Last-38]
}

const _TTy_name = "UNKNOWNEOFEQLNEQINCDECANDEQLOREQLXOREQLADDEQLSUBEQLMINUSLBRACKRBRACKLPARENRPARENCOLONFNBEGINENDRETURNIFTHENNOTSECTIONCONSTANTSDATAPROGRAMCONFIGURATIONBANKEDCOMMONI8ATIDENTNUM_FirstNUMDECIMALNUMHEXNUMBINARYNUM_Last"

var _TTy_index = [...]uint8{0, 7, 10, 13, 16, 19, 22, 28, 33, 39, 45, 51, 56, 62, 68, 74, 80, 85, 87, 92, 95, 101, 103, 107, 110, 117, 126, 130, 137, 150, 156, 162, 164, 166, 171, 180, 190, 196, 205, 213}

func (i TTy) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TTy_index)-1 {
		return "TTy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TTy_name[_TTy_index[idx]:_TTy_index[idx+1]]
}
